---
abstract: 'Add grammatical parsing features to Perl 5.10 regexes'
author:
  - 'Damian Conway <DCONWAY@CPAN.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Regexp-Grammars
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  version: '0'
version: '1.049'
